name: py312aiwatermark
channels:
  - nvidia
  - conda-forge
  - defaults
  - iopaint
dependencies:
  - python=3.12
  - pip
  - numpy
  - tqdm
  - loguru
  - click
  - pillow
  - opencv
  - pip:
      - --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu126
